source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'ZKit_Example' do
  pod 'ZKit/all', :path => '../'

  target 'ZKit_Tests' do
    inherit! :search_paths
    
  end
end
